#!/usr/bin/env bash

# Create the hass_writer user

# Usage: /bin/bash ./create_hass-writer_user_es <esurl> <esusername> <espassword>
#   <esurl> - The URL of the Elasticsearch instance (e.g., https://localhost:9200)
#   <esusername> - The existing admin user used to create the new user (e.g., hass)
#   <espassword> - The password for the admin user used to create the new user (e.g., hass)

esurl=$1
esusername=$2
espassword=$3

set -e

dir=$(dirname "$0")
/bin/bash "$dir/create_user_es" "$esurl" "$esusername" "$espassword" "hass_writer" "Home Assistant Writer" "changeme" "hass_writer"
