#!/usr/bin/env bash

# This script pulls the specified version of Elasticsearch Docker image from the elastic Docker registry.

# Usage: /bin/bash ./pull_es <version>
#   <esversion> - The version of Elasticsearch to pull (e.g., 7.10.2)
esversion=$1

set -e

start=$(date +%s)

docker pull docker.elastic.co/elasticsearch/elasticsearch:"$esversion" >/dev/null

end=$(date +%s)

echo -n " took $((end - start)) seconds"

echo
