#!/usr/bin/env bash

# Wait for Elasticsearch to be ready and print how long it took when it finally is ready
start=$(date +%s)
while true; do
  statuscode=$(curl -s -k -o /dev/null -w "%{http_code}" https://localhost:9200)
  #echo "Elasticsearch status code: $statuscode"
  echo -n "." # print a dot for each iteration
  if [ $statuscode -eq 401 ]; then
    break
  fi
  sleep 1
done
end=$(date +%s)

echo -n " (took $((end-start)) seconds)"

echo