#!/usr/bin/env bash

# This script extracts the code from the logs of a Docker container running Kibana.
# The code is in the format 'Go to http://0.0.0.0:5601/?code=317916 to get started.'

# Usage: /bin/bash ./get_kb_code <kbcontainer>
#   <kbcontainer> - The name or ID of the Kibana container

kbcontainer=$1

# Pull out the code from the logs
logs=$(docker logs "$kbcontainer")

# Extract the code using a regular expression
code=$(echo "$logs" | grep -oP 'code=\K[0-9]+')

# Print the extracted code
echo -n "$code"
