#!/usr/bin/env bash

# This script resets the elastic user password for Elasticsearch.

# Usage: /bin/bash ./reset_es_enrollment.sh <escontainer>
#   <escontainer> - The container id of the Elasticsearch instance

escontainer=$1

return=$(docker exec -it "$escontainer" /usr/share/elasticsearch/bin/elasticsearch-reset-password -u elastic --silent --batch)

# password is now a multiline return, filter out any lines that begin with WARNING:
password=$(echo -n "$return" | grep -v 'WARNING: ')

# return password and trim any leading/trailing whitespace
echo -n "$password" | tr -d '[:space:]'
