#!/usr/bin/env bash

# This script runs an Elasticsearch Docker container with the specified version.

# Usage: run_es <esversion>
#   <esversion> - The version of Elasticsearch to run (e.g., 7.10.2)

esversion=$1

set -e

docker run -p 9200:9200 --env discovery.type=single-node --name es01 --net elastic -q -d -m 1GB docker.elastic.co/elasticsearch/elasticsearch:"$esversion"
