#!/usr/bin/env bash

echo "Performing Environment Clean-up"

containers=("kb01" "es01")

for container in "${containers[@]}"; do
  # Check if the container exists
  if ! docker ps -a | grep -q "$container"; then
    continue
  fi

  echo "- Stopping and removing container $container"
  docker kill "$container" >/dev/null
  docker rm "$container" >/dev/null
done

# If the network exists, remove it
networks=$(docker network ls | grep -o "elastic")

if [ -n "$networks" ]; then
  echo "- Removing network $(echo "$networks" | tr -d '\n')"
  docker network rm elastic >/dev/null
fi
