#!/usr/bin/env bash

echo "Performing Environment Clean-up"

containers=$(sudo docker ps -a | grep "docker.elastic.co"  | awk '{ print $1 }')

# If containers returned a value, kill and remove them
if [ -n "$containers" ]; then
  echo "- Stopping and removing containers $(echo $containers | tr -d '\n')"
  docker kill $containers > /dev/null
  docker rm $containers > /dev/null
fi

# If the network exists, remove it
networks=$(docker network ls | grep -o "elastic")

if [ -n "$networks" ]; then
  echo "- Removing network $(echo $networks | tr -d '\n')"
  docker network rm elastic > /dev/null
fi

