#!/usr/bin/env bash

# get the current directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

sudo /bin/bash "$DIR/clean_ek"
sudo /bin/bash "$DIR/helpers/es8/bootstrap_ek" "8.13.0"