name: "Validate and Test"
on:
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Download repo
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        name: Setup Python
      - uses: actions/cache@v2
        name: Cache
        with:
          path: |
            ~/.cache/pip
          key: custom-component-ci
  
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - uses: "actions/checkout@v2"

      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"

      - name: Hassfest validation
        uses: "home-assistant/actions/hassfest@master"
  
      - name: Test with pytest
        run: |
          pytest
      - name: Test with flake8
        run: |
          flake8 .
      - name: Test with isort
        run: |
          isort .
      - name: Test with black
        run: |
          black .
